spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://host.docker.internal:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=room-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://host.docker.internal:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/rooms/**

spring.cloud.gateway.server.webflux.routes[2].id=reservation-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://host.docker.internal:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/reservations/**

spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://host.docker.internal:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webflux.routes[4].id=review-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://host.docker.internal:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/reviews/**

spring.cloud.gateway.server.webflux.routes[5].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://host.docker.internal:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/recommend/**